#!/usr/bin/env python3
"""
Quick setup wizard for GeoJob-Sentinel
Helps configure the application interactively
"""

import sys
from pathlib import Path

def print_banner():
    print("=" * 60)
    print("🌍 GeoJob-Sentinel Setup Wizard")
    print("=" * 60)
    print()

def check_config():
    """Check if config.yaml exists"""
    config_path = Path("config.yaml")
    example_path = Path("config.example.yaml")
    
    if config_path.exists():
        print("✓ config.yaml already exists")
        overwrite = input("Do you want to reconfigure? (y/n): ").lower()
        if overwrite != 'y':
            return True
    
    if not example_path.exists():
        print("✗ config.example.yaml not found!")
        return False
    
    return False

def get_input(prompt, required=True, default=None):
    """Get user input with validation"""
    while True:
        if default:
            value = input(f"{prompt} [{default}]: ").strip()
            if not value:
                return default
        else:
            value = input(f"{prompt}: ").strip()
        
        if value or not required:
            return value
        
        print("This field is required. Please enter a value.")

def setup_config():
    """Interactive configuration setup"""
    print("\n📝 Configuration Setup\n")
    
    # Discord Webhook
    print("1. Discord Webhook URL")
    print("   Get from: Discord Server → Settings → Integrations → Webhooks")
    webhook = get_input("   Enter your Discord webhook URL")
    
    # Serper API Key
    print("\n2. Serper.dev API Key")
    print("   Get from: https://serper.dev (Free tier: 2,500 searches/month)")
    serper_key = get_input("   Enter your Serper.dev API key")
    
    # Company Slugs
    print("\n3. Company Slugs (optional - press Enter to use defaults)")
    print("   Example: esri, mapbox, planet")
    print("   Find slugs at: https://boards.greenhouse.io/COMPANY_NAME")
    companies = get_input("   Enter company slugs (comma-separated)", required=False,
                         default="esri,planet,mapbox,carto,nearmap")
    
    # Create config.yaml
    company_list = [f'    - "{slug.strip()}"' for slug in companies.split(',')]
    company_yaml = '\n'.join(company_list)
    
    config_content = f"""# GeoJob-Sentinel Configuration File
# Auto-generated by setup wizard

database:
  path: "geojob_sentinel.db"

discord:
  webhook_url: "{webhook}"

serper:
  api_key: "{serper_key}"
  custom_dorks:
    - 'site:myworkdayjobs.com "GIS Specialist" OR "GIS Analyst" -senior -lead after:2025-01-01'
    - 'site:myworkdayjobs.com "Geospatial Analyst" -senior -manager after:2025-01-01'

ats:
  company_slugs:
{company_yaml}

filters:
  required_keywords:
    - "gis"
    - "geospatial"
    - "spatial"
    - "mapping"
  
  negative_keywords:
    - "senior"
    - "sr."
    - "sr "
    - "iii"
    - "iv"
    - "lead"
    - "manager"
    - "director"
    - "principal"
    - "chief"
    - "head of"
    - "vp"
    - "vice president"
    - "executive"
    - "architect"

logging:
  level: "INFO"
  file: "geojob_sentinel.log"
"""
    
    # Write config file
    with open("config.yaml", "w") as f:
        f.write(config_content)
    
    print("\n✓ config.yaml created successfully!")

def check_dependencies():
    """Check if dependencies are installed"""
    print("\n📦 Checking Dependencies\n")
    
    try:
        import requests
        import yaml
        import fake_useragent
        from discord_webhook import DiscordWebhook
        print("✓ All dependencies installed")
        return True
    except ImportError as e:
        print(f"✗ Missing dependencies: {e}")
        print("\nInstalling dependencies...")
        import subprocess
        result = subprocess.run([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])
        return result.returncode == 0

def main():
    print_banner()
    
    # Step 1: Check/create config
    if not check_config():
        setup_config()
    
    # Step 2: Check dependencies
    if not check_dependencies():
        print("\n✗ Failed to install dependencies")
        return 1
    
    # Step 3: Ready to go
    print("\n" + "=" * 60)
    print("✅ Setup Complete!")
    print("=" * 60)
    print("\nYou can now run GeoJob-Sentinel:")
    print("  python geojob_sentinel.py")
    print("\nOr use the batch file:")
    print("  run_scanner.bat")
    print("\nFor automation setup, see README.md")
    print()
    
    return 0

if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n✗ Error during setup: {e}")
        sys.exit(1)
